#!/bin/bash
set -e

CONVEX_DART_DEFINE="${CONVEX_URL:-${NEXT_PUBLIC_CONVEX_URL:-}}"
CLERK_PUBLISHABLE_KEY_DART_DEFINE="${CLERK_PUBLISHABLE_KEY:-${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}}"
TUBEFLOW_APP_URL_DART_DEFINE="${TUBEFLOW_APP_URL:-${TUBEFLOW_WEB_URL:-https://app.tubeflow.winflowz.com}}"

flutter/bin/flutter build web \
  --dart-define=CONVEX_URL=$CONVEX_DART_DEFINE \
  --dart-define=CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DART_DEFINE \
  --dart-define=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DART_DEFINE \
  --dart-define=TUBEFLOW_APP_URL=$TUBEFLOW_APP_URL_DART_DEFINE \
  --dart-define=TUBEFLOW_WEB_URL=$TUBEFLOW_APP_URL_DART_DEFINE \
  2>&1 \
|| {
  echo '=== DART ERRORS ==='
  flutter/bin/flutter analyze --no-pub lib web 2>&1 | tail -50
  exit 1
}
