#!/bin/bash
set -e

CONVEX_DART_DEFINE="${CONVEX_URL:-${NEXT_PUBLIC_CONVEX_URL:-}}"
FIREBASE_API_KEY_DART_DEFINE="${FIREBASE_API_KEY:-}"
FIREBASE_AUTH_DOMAIN_DART_DEFINE="${FIREBASE_AUTH_DOMAIN:-}"
FIREBASE_PROJECT_ID_DART_DEFINE="${FIREBASE_PROJECT_ID:-}"
FIREBASE_STORAGE_BUCKET_DART_DEFINE="${FIREBASE_STORAGE_BUCKET:-}"
FIREBASE_MESSAGING_SENDER_ID_DART_DEFINE="${FIREBASE_MESSAGING_SENDER_ID:-}"
FIREBASE_APP_ID_DART_DEFINE="${FIREBASE_APP_ID:-}"
REPLAYGLOWZ_APP_URL_DART_DEFINE="${REPLAYGLOWZ_APP_URL:-${TUBEFLOW_APP_URL:-${TUBEFLOW_WEB_URL:-https://app.replayglowz.com}}}"
BUILD_COMMIT_SHA_DART_DEFINE="${BUILD_COMMIT_SHA:-${VERCEL_GIT_COMMIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}}"
BUILD_ENVIRONMENT_DART_DEFINE="${BUILD_ENVIRONMENT:-${VERCEL_ENV:-local}}"
BUILD_TIMESTAMP_DART_DEFINE="${BUILD_TIMESTAMP:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
SENTRY_DSN_DART_DEFINE="${SENTRY_DSN:-${NEXT_PUBLIC_SENTRY_DSN:-}}"
SENTRY_ENVIRONMENT_DART_DEFINE="${SENTRY_ENVIRONMENT:-$BUILD_ENVIRONMENT_DART_DEFINE}"
SENTRY_RELEASE_DART_DEFINE="${SENTRY_RELEASE:-replayglowz_app@$BUILD_COMMIT_SHA_DART_DEFINE}"
SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE="${SENTRY_TRACES_SAMPLE_RATE:-0}"
SENTRY_DEBUG_DART_DEFINE="${SENTRY_DEBUG:-false}"
FLUTTER_BIN="${FLUTTER_BIN:-flutter}"
if [ -x "flutter/bin/flutter" ]; then
  FLUTTER_BIN="flutter/bin/flutter"
fi

"$FLUTTER_BIN" build web \
  --dart-define=CONVEX_URL=$CONVEX_DART_DEFINE \
  --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY_DART_DEFINE \
  --dart-define=FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN_DART_DEFINE \
  --dart-define=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID_DART_DEFINE \
  --dart-define=FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET_DART_DEFINE \
  --dart-define=FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID_DART_DEFINE \
  --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID_DART_DEFINE \
  --dart-define=REPLAYGLOWZ_APP_URL=$REPLAYGLOWZ_APP_URL_DART_DEFINE \
  --dart-define=TUBEFLOW_APP_URL=$REPLAYGLOWZ_APP_URL_DART_DEFINE \
  --dart-define=TUBEFLOW_WEB_URL=$REPLAYGLOWZ_APP_URL_DART_DEFINE \
  --dart-define=BUILD_COMMIT_SHA=$BUILD_COMMIT_SHA_DART_DEFINE \
  --dart-define=BUILD_ENVIRONMENT=$BUILD_ENVIRONMENT_DART_DEFINE \
  --dart-define=BUILD_TIMESTAMP=$BUILD_TIMESTAMP_DART_DEFINE \
  --dart-define=SENTRY_DSN=$SENTRY_DSN_DART_DEFINE \
  --dart-define=NEXT_PUBLIC_SENTRY_DSN=$SENTRY_DSN_DART_DEFINE \
  --dart-define=SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT_DART_DEFINE \
  --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE_DART_DEFINE \
  --dart-define=SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE \
  --dart-define=SENTRY_DEBUG=$SENTRY_DEBUG_DART_DEFINE \
  2>&1 \
|| {
  echo '=== DART ERRORS ==='
  "$FLUTTER_BIN" analyze --no-pub lib web 2>&1 | tail -50
  exit 1
}
