#!/bin/bash
set -e

CONVEX_DART_DEFINE="${CONVEX_URL:-${NEXT_PUBLIC_CONVEX_URL:-}}"
CLERK_PUBLISHABLE_KEY_DART_DEFINE="${CLERK_PUBLISHABLE_KEY:-${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}}"
TUBEFLOW_APP_URL_DART_DEFINE="${TUBEFLOW_APP_URL:-${TUBEFLOW_WEB_URL:-https://app.tubeflow.winflowz.com}}"
CLERK_HOSTED_SIGN_IN_URL_DART_DEFINE="${CLERK_HOSTED_SIGN_IN_URL:-}"
BUILD_COMMIT_SHA_DART_DEFINE="${BUILD_COMMIT_SHA:-${VERCEL_GIT_COMMIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}}"
BUILD_ENVIRONMENT_DART_DEFINE="${BUILD_ENVIRONMENT:-${VERCEL_ENV:-local}}"
BUILD_TIMESTAMP_DART_DEFINE="${BUILD_TIMESTAMP:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
SENTRY_DSN_DART_DEFINE="${SENTRY_DSN:-${NEXT_PUBLIC_SENTRY_DSN:-}}"
SENTRY_ENVIRONMENT_DART_DEFINE="${SENTRY_ENVIRONMENT:-$BUILD_ENVIRONMENT_DART_DEFINE}"
SENTRY_RELEASE_DART_DEFINE="${SENTRY_RELEASE:-tubeflow_app@$BUILD_COMMIT_SHA_DART_DEFINE}"
SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE="${SENTRY_TRACES_SAMPLE_RATE:-0}"
SENTRY_DEBUG_DART_DEFINE="${SENTRY_DEBUG:-false}"

flutter/bin/flutter build web \
  --dart-define=CONVEX_URL=$CONVEX_DART_DEFINE \
  --dart-define=CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DART_DEFINE \
  --dart-define=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DART_DEFINE \
  --dart-define=TUBEFLOW_APP_URL=$TUBEFLOW_APP_URL_DART_DEFINE \
  --dart-define=TUBEFLOW_WEB_URL=$TUBEFLOW_APP_URL_DART_DEFINE \
  --dart-define=CLERK_HOSTED_SIGN_IN_URL=$CLERK_HOSTED_SIGN_IN_URL_DART_DEFINE \
  --dart-define=BUILD_COMMIT_SHA=$BUILD_COMMIT_SHA_DART_DEFINE \
  --dart-define=BUILD_ENVIRONMENT=$BUILD_ENVIRONMENT_DART_DEFINE \
  --dart-define=BUILD_TIMESTAMP=$BUILD_TIMESTAMP_DART_DEFINE \
  --dart-define=SENTRY_DSN=$SENTRY_DSN_DART_DEFINE \
  --dart-define=NEXT_PUBLIC_SENTRY_DSN=$SENTRY_DSN_DART_DEFINE \
  --dart-define=SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT_DART_DEFINE \
  --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE_DART_DEFINE \
  --dart-define=SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE \
  --dart-define=SENTRY_DEBUG=$SENTRY_DEBUG_DART_DEFINE \
  2>&1 \
|| {
  echo '=== DART ERRORS ==='
  flutter/bin/flutter analyze --no-pub lib web 2>&1 | tail -50
  exit 1
}
